# STORYSTREAM | Development Environment
# ---------------------------------------------------------
# This setup enables "Hot Reloading" via Volumes.
# Save your changes in WebStorm and just refresh the browser.

services:
  storystream_web_server:
    # Using the official Nginx Alpine image as our clean base
    image: nginx:alpine
    container_name: container_storystream_development

    # Port mapping: localhost:8080 -> Container:80
    ports:
      - "8080:80"

    # THE HOT-RELOAD MIRROR:
    # Maps our local directory to the Nginx web root.
    # No need for manual builds during development.
    volumes:
      - .:/usr/share/nginx/html

    # Ensures the server stays up and running
    restart: always